
-- Schema for users table (sqlite)
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE,
	email TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Index for quick lookup by email
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Example insert (replace PASSWORD_HASH with a bcrypt/pbkdf2 hash generated by your backend):
INSERT OR IGNORE INTO users (username, email, password_hash) VALUES ('demo', 'demo@vinylvault.test', 'PASSWORD_HASH');

-- Notes:
-- Use a secure password hashing method (bcrypt / argon2 / pbkdf2). Example Python creation flow:
-- from werkzeug.security import generate_password_hash
-- password_hash = generate_password_hash('yourPassword')
-- then insert that hash into the `password_hash` column.

